version: '3'

# RapidFab.xyz Task-based CI Pipeline
# Usage: task ci (or just: task)
# Documentation: tests/CLAUDE.md

vars:
  API_DIR: services/api
  UPLOAD_DIR: services/upload
  TESTS_DIR: tests
  E2E_DIR: tests/e2e

tasks:
  default:
    desc: Run full CI pipeline (default)
    cmds:
      - task: ci

  ci:
    desc: Full CI pipeline - run after agent work
    summary: |
      Runs complete CI pipeline:
      1. Stop Docker if running
      2. Format check (API + Upload services)
      3. Linter (API + Upload services)
      4. Unit tests (API + Upload services)
      5. Build Docker images
      6. Deploy Docker stack
      7. Wait for services healthy
      8. Integration tests (API + Upload services - requires running Docker)
      9. E2E tests (auto-discovered from tests/e2e/*_test.sh)
      10. Cleanup Docker

      Exit code: 0 = all passed, non-zero = failures
      AGENTS CANNOT COMMIT IF THIS FAILS!
    silent: true
    cmds:
      - echo "🚀 Running CI..."
      - docker-compose -f docker-compose.minimal.yml down 2>/dev/null || true
      - task: fmt
      - task: fmt:upload
      - task: lint
      - task: lint:upload
      - task: test:unit
      - task: test:unit:upload
      - docker-compose -f docker-compose.minimal.yml build
      - docker-compose -f docker-compose.minimal.yml up -d >/dev/null 2>&1
      - task: docker:wait-healthy
      - task: test:integration
      - task: test:integration:upload
      - task: test:e2e
      - docker-compose -f docker-compose.minimal.yml down -v >/dev/null 2>&1
      - echo "✅ CI passed"

  fmt:
    desc: Check code formatting
    dir: "{{.API_DIR}}"
    silent: true
    cmds:
      - cargo fmt --all -- --check

  fmt:fix:
    desc: Auto-fix code formatting
    dir: "{{.API_DIR}}"
    cmds:
      - echo "📝 Auto-fixing code format..."
      - cargo fmt --all
      - echo "✅ Format fixed"

  lint:
    desc: Run linter (clippy)
    dir: "{{.API_DIR}}"
    silent: false
    env:
      SQLX_OFFLINE: "true"
    cmds:
      - cargo clippy --all-targets -- -D warnings

  test:
    desc: Run Rust tests (unit + integration)
    dir: "{{.API_DIR}}"
    env:
      SQLX_OFFLINE: "true"
    cmds:
      - echo "🧪 Running Rust tests..."
      - cargo test --lib --bins
      - cargo test --test '*' -- --test-threads=1
      - echo "✅ Rust tests passed"

  test:unit:
    desc: Run only unit tests
    dir: "{{.API_DIR}}"
    silent: false
    env:
      SQLX_OFFLINE: "true"
    cmds:
      - cargo test --lib --bins

  test:integration:
    desc: Run only integration tests
    dir: "{{.API_DIR}}"
    silent: false
    env:
      SQLX_OFFLINE: "true"
    cmds:
      - cargo test --test '*' -- --test-threads=1

  fmt:upload:
    desc: Check code formatting (upload service)
    dir: "{{.UPLOAD_DIR}}"
    silent: true
    cmds:
      - cargo fmt --all -- --check

  lint:upload:
    desc: Run linter (upload service)
    dir: "{{.UPLOAD_DIR}}"
    silent: false
    env:
      SQLX_OFFLINE: "true"
    cmds:
      - cargo clippy --all-targets -- -D warnings

  test:unit:upload:
    desc: Run unit tests (upload service)
    dir: "{{.UPLOAD_DIR}}"
    silent: false
    env:
      SQLX_OFFLINE: "true"
    cmds:
      - cargo test --lib --bins

  test:integration:upload:
    desc: Run integration tests (upload service)
    dir: "{{.UPLOAD_DIR}}"
    silent: false
    env:
      SQLX_OFFLINE: "true"
    cmds:
      - cargo test --test '*' -- --ignored --test-threads=1

  test:e2e:
    desc: Run E2E tests (auto-discovery)
    silent: false
    cmds:
      - ./tests/test-e2e.sh

  build:
    desc: Build API in release mode
    dir: "{{.API_DIR}}"
    cmds:
      - echo "🔨 Building API (release mode)..."
      - cargo build --release
      - echo "✅ Build complete"

  run:
    desc: Run API locally
    dir: "{{.API_DIR}}"
    cmds:
      - echo "🚀 Starting API..."
      - RUST_LOG=info cargo run

  clean:
    desc: Clean build artifacts
    dir: "{{.API_DIR}}"
    cmds:
      - echo "🧹 Cleaning build artifacts..."
      - cargo clean
      - echo "✅ Cleanup complete"

  docker:build:
    desc: Build Docker images
    cmds:
      - echo "🐳 Building Docker images..."
      - docker-compose build
      - echo "✅ Docker build complete"

  docker:up:
    desc: Start Docker services
    cmds:
      - echo "🐳 Starting Docker services..."
      - docker-compose up -d
      - echo "✅ Services started"

  docker:down:
    desc: Stop Docker services
    cmds:
      - echo "🐳 Stopping Docker services..."
      - docker-compose down
      - echo "✅ Services stopped"

  dev:
    desc: Start full dev stack (minimal + observability)
    cmds:
      - echo "🚀 Starting dev stack..."
      - docker-compose -f docker-compose.minimal.yml -f docker-compose.obs.yml up -d
      - |
        echo "✅ Services started"
        echo "API http://localhost:8080"
        echo "Upload http://localhost:8082"
        echo "Grafana http://localhost:3000 (admin/admin)"
        echo "Prometheus http://localhost:9090"
        echo "PGWeb http://localhost:8081"

  docker:wait-healthy:
    desc: Wait for services to be healthy
    silent: true
    cmds:
      - |
        TIMEOUT=60
        elapsed=0
        while [ $elapsed -lt $TIMEOUT ]; do
          api_healthy=$(curl -sf http://localhost:8080/health/healthz > /dev/null 2>&1 && echo "ok" || echo "fail")
          upload_healthy=$(curl -sf http://localhost:8082/health > /dev/null 2>&1 && echo "ok" || echo "fail")

          if [ "$api_healthy" = "ok" ] && [ "$upload_healthy" = "ok" ]; then
            exit 0
          fi

          sleep 2
          elapsed=$((elapsed + 2))
        done

        echo "❌ Timeout waiting for services"
        echo "API status: $api_healthy"
        echo "Upload status: $upload_healthy"
        docker-compose -f docker-compose.minimal.yml logs
        exit 1

  help:
    desc: Show available tasks
    cmds:
      - task --list
